global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]

  - job_name: "prediction-consumer"
    metrics_path: /metrics
    static_configs:
      - targets: ["prediction-consumer:8001"]

  - job_name: "db-consumer"
    metrics_path: /metrics
    static_configs:
      - targets: ["db-consumer:8002"]